### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [jridley11/Tea-Cozy#5]
Grade: Exceeds Expectations

This is a fantastically concise, clean, and clear use of both HTML and CSS. You provide further clarity using comments, and your code is generally spaced and indented with consistency, which gives a nice flow to your code.

From here, there are ways to bring your CSS to the next level. It's usually best to give elements dimensions with % over px (i.e. width: 80%, not 60px). This will make your app responsive when it's used on different screen sizes (small tablet, phone screen, computer desktop, etc.). Also, instead of using colors like 'black' or 'seashell', I usually go on Coolors.co to find interesting color palettes that enhance the app visually. I also like to use Google Fonts to find more lively type than Helvetica and the like. These are just some ideas! This is a great project, congratulations!

**Comment by jridley11** [comment]
Hi blerude! Thanks so much for your constructive and encouraging feedback. I really appreciate you taking the time to explain how I can improve my coding as well as highlighting the things that I am doing well at. Thank you for your recommendations regarding the use of % over px and utilising Coolors.co as well as Google Fonts. I have now bookmarked these sites for future reference and use.

Thanks again and best regards,
Jonathan
